title: Microcosims
description: "A game dedicated to items and crafts"
author:
  name: "Null Reference"
  email: "nullreference8@gmail.com"
  url: "https://nullreference8.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Null Reference"
year : "2022"
